-- MySQL Script generated by MySQL Workbench
-- 06/07/17 19:40:25
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Table `usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `login` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `produtos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `preco_venda` FLOAT NULL,
  `preco_compra` FLOAT NULL,
  `desconto` FLOAT NULL,
  `estoque` INT NULL,
  `ativo` INT NULL,
  `idusuario` INT NOT NULL,
  `descricao` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_produtos_usuários1_idx` (`idusuario` ASC),
  CONSTRAINT `fk_produtos_usuários1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fotos_produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fotos_produtos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `foto` VARCHAR(45) NULL,
  `idproduto` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_fotos_produtos_produtos_idx` (`idproduto` ASC),
  CONSTRAINT `fk_fotos_produtos_produtos`
    FOREIGN KEY (`idproduto`)
    REFERENCES `produtos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
